name: CI
on:
  # To be fixed
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
jobs:
  build:
    name: test Node ${{ matrix.node }} ${{ matrix.os }}
    timeout-minutes: 15

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x']
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: corepack enable && pnpm i

      - name: Test
        run: npm test -- --forceExit || npm test -- --forceExit || npm test -- --forceExit
